name: Terminal (mac)

on: 
  workflow_dispatch:

jobs:
  running:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Running terminal server...
      run: curl -sSf https://sshx.io/get | sh && sshx
